### ISSUE TITLE
Open payment channel between taker and maker

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#10]
Before funding a cfd contract using a lightning transaction, the taker and the maker need to open a payment channel

**Comment by holzeis** [comment]
@bonomat whats the status of dual-funded channels? last time you mentioned this is not yet supported by ldk? are we planning to build that?

Alternatively, would it work to open two payment one inbound and one outbound?

**Comment by bonomat** [comment]
Dual-funded channels are still in the works on rust-lightning. In the meantime (and for the time being) we can use one-sided funded channels. The user then sends us their funds and we open a channel with them. It's not optimal because there is some trust involved but it should be good enough for now. 

> Alternatively, would it work to open two payment one inbound and one outbound?

For that we would need to be able to split DLCs across multiple channels. Not an easy task but something we should do in the long run.

**Comment by holzeis** [comment]
Dependent on #82 and #89

**Comment by bonomat** [comment]
I want to point out a potential problem which up in https://github.com/itchysats/10101/issues/113#issuecomment-1302804794: 

For trading CFDs we need a channel with balances on both sides. In an ideal world we would have dual-funded channels but this is not a thing yet. 

Since we don't have this we came up with a solution where the `maker` will open the channel to the `taker` and the `taker` send all channel funds to the maker on-chain in a trusted way. However, we assume that the `maker` will run on a server and the `taker` will run on a phone. Afaik it is hard to connect to a phone because your mobile provider might block the ports. 
If this is true, than we cannot easily do the proposed solution. 

The simplest alternative to this I could come up with so far is to turn things around: 
1. the `taker` tells the `maker` he wants to open a channel and provides him an address, 
2. the `maker` sends on-chain funds to the `taker`
3. the `taker` opens the channel to the maker.

This obviously really really bad but could work for the time being. 

An alternative solution: We could run 10101 on a custom Signet for the time being and simply give the `taker` alot of money. (as proposed by @luckysori). That way the `taker` could simply open the channel to the `maker` and give us money, no need to rebalance. 

What do you guys think?

**Comment by holzeis** [comment]
Well if its just the issue of reaching the phone, couldn't we use services like firebase to tell the mobile wallet to sign something and send it to the maker for opening the channel? Alternatively we could also implement a mediator service (could be the maker in the beginning) which will keep an encrypted inbox for the mobile takers. (The mobile wallet could then poll for new messages).

**Comment by bonomat** [comment]
LDK seems to be quite flexible in regards to the network stack: either build your own or use what they have: They have a tokio-based tcp connection library which is ready to use. So unless we build our own I don't think this can be easily done.

**Comment by da-kami** [comment]
I think to come to a conclusion it would be good to define what we expect as outcome of the tournament more clearly, as in: 

- Do we expect to run this *at least* on testnet or is signet good enough?
- Do we expect to actually run it on one of our devices or just within the simulator? (Can we make the simulator reachable? I guess yes...)
- Do we expect to ship on e.g. Testflight so that others can install the POC?

> The simplest alternative to this I could come up with so far is to turn things around:
> 
>     1. the `taker` tells the `maker` he wants to open a channel and provides him an address,
> 
>     2. the `maker` sends on-chain funds to the `taker`
> 
>     3. the `taker` opens the channel to the maker.
> 

Obviously not a solution we should use in production, but for a demo I would not mind to turn it around and let the taker open the channel. If this is just for the purpose of a demo I'm fine with it.

> This obviously really really bad but could work for the time being.
> 
> An alternative solution: We could run 10101 on a custom Signet for the time being and simply give the `taker` alot of money. (as proposed by @luckysori). That way the `taker` could simply open the channel to the `maker` and give us money, no need to rebalance.
> 
> What do you guys think?

If we decide that a signet demo is good enough this might be the better solution to go for, because this is more in line of what the flow would actually be. I think this would simplify things rather than making them more complicated.

**Comment by holzeis** [comment]
As discussed in the objective alignment, for this ticket and for the tournament of legends we are going with a channel created by the `taker` and fix later.

1. the `taker` tells the `maker` he wants to open a channel and provides him an address,
2. the `maker` sends on-chain funds to the `taker`
3. the `taker` opens the channel to the maker.

**Comment by bonomat** [comment]
One question: Since the wireframes does not have an action/screen for this: how is a channel created? Is this done automatically or through user input?

- automatically might be hard, because we will need to figure out _when_. Once money arrives in the wallet might not be the best idea because the user might want to deposit money in 2+ transactions before opening a wallet
- through user input: we should potentially design a screen in figma for that

**Comment by holzeis** [comment]
> One question: Since the wireframes does not have an action/screen for this: how is a channel created? Is this done automatically or through user input?
> 
>     * automatically might be hard, because we will need to figure out _when_. Once money arrives in the wallet might not be the best idea because the user might want to deposit money in 2+ transactions before opening a wallet
> 
>     * through user input: we should potentially design a screen in figma for that

Since this is anyways a temporary feature, I wouldn't go into any UX improvements and go with the automated approach.

**Comment by bonomat** [comment]
The flow as outlined in your [comment here](https://github.com/itchysats/10101/issues/10#issuecomment-1305264551) is temporary but generally opening a channel is not. We haven't modeled how a channel is being created yet.

**Comment by da-kami** [comment]
I will see to come up with wireframe screens for this, I think the relevant ticket is #113 ?
Or are #10 and #113 the same ticket? :)

> automatically might be hard, because we will need to figure out when. Once money arrives in the wallet might not be the best idea because the user might want to deposit money in 2+ transactions before opening a wallet

@bonomat what's the reasoning behind this? Why is it important that the user wants to us 2+ transactions? Do you mean confirmations/blocks?

I think automated would be best for now, I would not want to show this functionality too much.

Here is my summary of the steps once more:

1. The taker contacts the maker to create initial channel, I imagine these messages
    1. Taker -> Maker: Hello
    1. Maker -> Taker: Maker Lightning Node address
    1. Taker -> Maker: Intended capacity for channel (?)
    1. Maker -> Taker: OK
    1. Taker -> Maker: Address for BTC to go
3. The maker funds the address provided by the taker
4. The taker opens the channel to the maker by locking up the funds

User interface: 

The taker sees a screen `Create Channel` where the taker can select:

- The amount the taker intends to use for trading (?)
- The maker to connect to - currently only one maker that is hardcoded
- A button `Create Channel`

The rest is done in the background, but we could provide some status update that shows the taker the process.

**Comment by da-kami** [comment]
![OpenChannelJourney](https://user-images.githubusercontent.com/5557790/200470112-cd46769c-ab37-45a3-a585-df3cfdf79a77.png)

**Comment by da-kami** [comment]
@holzeis I assigned you you to this ticket because I think you are the one working on it primarily now. 

Note: The screens are implemented besides the payment history actually being wired in, I would keep that tracked in #165

**Comment by da-kami** [comment]
This ticket still has several sub-tasks related to "opening the channel" that were not fully addressed. In a effort to know what is yet to be done I captured these tickets separately: 

https://github.com/itchysats/10101/issues/199
https://github.com/itchysats/10101/issues/198 (this is relevant because it defines the channel capacity for now)

**Comment by da-kami** [comment]
@holzeis I think we can close this ticket in favor for the more specific follow-up tickets.
