### ISSUE TITLE
Subscribe to maker to fetch btcusd bid, ask and index price

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#106]

**Comment by bonomat** [comment]
Can you add some more context why this is needed? Imho the btcusd price should come from the counterparty.

**Comment by da-kami** [comment]
To add a bit more context let's reflect on what we have done and what we should do in terms of price on the taker side. 

Here is what we have in ItchySats to date:

1. BitMEX index price for reference (UI only)
2. Maker bid/ask price for opening a position (i.e. the offer price)
3. BitMEX bid/ask price for closing a position (taker picks that price when proposing collab settlement)
4. BitMEX bid/ask price for calculating the P/L 

We have argued in the past that using the BitMEX price for 3. and 4. doesn't make sense, because in the end the maker makes the price, so the taker should just use the current price of the maker not the BitMEX price. P/L reflects the collaborative scenario, so the maker's price is the only one that makes sense for this scenario.
Note: One could argue that, given the non-custodial setup where we want to minimize trust, the taker should have means to evaluate if the maker's price is completely off - but that does not require automation during protocol execution. In the end the only choices the taker has are: Either accept the price of the maker, or force-close.

That said, as @bonomat has stated, from the taker's perspective there is no other price than the maker's - except the reference index price that can be displayed (purely for reference to check the maker's price for sanity).

**Comment by holzeis** [comment]
Fair enough, I've adapted the title of this ticket - reflecting that the prices should come from the maker 😉

**Comment by da-kami** [comment]
nit: I think the index price should come from the index itself, not the maker. But we can ignore that for now.
