### ISSUE TITLE
taker balance is 0 before `open_channel` succeds

### ISSUE THREAD

**Issue by klochowicz** [itchysats/10101#347]
Even if funded previously, the taker's balance is 0 until the other transaction gets confirmed:

![image](https://user-images.githubusercontent.com/8319440/203690447-0baf8dd8-b331-449b-9a2e-b6e64eac64d0.png)

**Comment by da-kami** [comment]
This is because we use `confirmed` balance to display the on-chain balance, and with only one unspent output (that is then used for opening the channel) you don't have any confirmed BTC until the transaction is confirmed. 

The *proper* solution for this is to have an indicator on each balance that shows if the balance is confirmed or not, and display unconfirmed balance in between. This, however, will require some design, because it can become cluttered with yet another dimension of indication on the on-chain balance. We could give it a try though.
