### ISSUE TITLE
Build ldk node (taker)

### ISSUE THREAD

**Issue by holzeis** [itchysats/10101#82]
https://lightningdevkit.org/tutorials/build_a_node_in_rust/

- run ldk node on the phone

**Comment by bonomat** [comment]
2 notes: 
1. We will need to receive on-chain funds to open a channel first. 
2. Receiving off-chain funds might be hard because for that we will need to re-balance our channel or have someone else open a channel with us.

I propose to change this ticket to: create a channel with a fixed node with all the funds in the wallet.

**Comment by klochowicz** [comment]
I started working on it (with bitcoind, instead of electrum server in the beginning), but I found out really hard to debug things without logging infrastructure, so I'll proceed to #83 first

**Comment by holzeis** [comment]
> I propose to change this ticket to: create a channel with a fixed node with all the funds in the wallet.

I guess the first step is to get an ldk node running in a second step we can open a channel - https://github.com/itchysats/10101/issues/10

But please correct if this split is nonsense.

**Comment by bonomat** [comment]
Makes totally sense :)

**Comment by bonomat** [comment]
One question: Since the wireframes does not have an action/screen for this: how is a channel created? Is this done automatically or through user input?

- automatically might be hard, because we will need to figure out _when_. Once money arrives in the wallet might not be the best idea because the user might want to deposit money in 2+ transactions before opening a wallet
- through user input: we should potentially design a screen in figma for that

**Comment by bonomat** [comment]
I thin this ticket can be closed in favor of https://github.com/itchysats/10101/issues/10

**Comment by klochowicz** [comment]
closing this ticket, as the initial lightning node got implemented #163
